blank_issues_enabled: false
contact_links:
  - name: \U0001F6A8 Security issue
    url: https://ckeditor.com/contact
    about: |
      Please **DO NOT report security issues here**,
      use the contact form at https://ckeditor.com/contact/ instead.
