name: Update CKEditor 5 blob dev

on:
    push:
        branches:
            - fullScreen

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: "https://npm.pkg.github.com"
                  scope: "@ftrprf"
            - name: Build editor
              run: cd ./packages/ckeditor5-build-decoupled-document && pwd && npm install && npm run build
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - name: upload to storage
              env:
                  AZURE_STORAGE_ACCOUNT: "ckeditorbuild"
                  AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_BLOB_STORAGE_DEV_CONNECTION_STRING }}
              run: az storage blob upload -f ./packages/ckeditor5-build-decoupled-document/build/ckeditor.js -c \ckeditor -n ckeditor5fullScreen.js --overwrite
